services:
  psql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - psql_volume:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: "./backend/.env.docker"
    environment:
      DB_HOST: "psql"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - psql

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  psql_volume:
    driver: local
