name: IAmHuman Bot

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Sets ./web directory as working-directory to all
        # run steps in this job
        working-directory: ./web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0
          cache: "npm"
          cache-dependency-path: ./web/package.json
      - name: Install dependencies
        run: npm ci
      - name: build target
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./web/dist

  deploy-frontend:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build-backend:
    runs-on: self-hosted
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Deploy to Self-hosted Server
        run: |
          docker compose -f ./backend/compose.yaml down -v
          docker compose -f ./backend/compose.yaml up -d --build
